import { KumaRegistry } from "@kuma-ui/next-plugin/registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head prefix="og: https://ogp.me/ns#">
        <meta property="og:url" content="https://ramda.io" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="ramda.io" />
        <meta property="og:site_name" content="ramda.io" />
        <meta property="og:image" content="https://ramda.io/ogp.png" />
        <meta name="twitter:card" content="summary" />
        <title>ramda.io</title>
      </head>
      <body className={inter.className}>
        <KumaRegistry>{children}</KumaRegistry>
        <Analytics />
      </body>
    </html>
  );
}
